require: rubocop-rspec

Style/Documentation:
  Enabled: false

Style/MixinUsage:
  Enabled: false

Metrics/LineLength:
  Max: 100

Metrics/MethodLength:
  Max: 50

Metrics/BlockLength:
  Max: 150

Metrics/ModuleLength:
  Max: 200

Metrics/AbcSize:
  Max: 70

Lint/UselessAssignment:
  Exclude:
    - spec/data/*

RSpec/ExampleLength:
  Max: 100

RSpec/MultipleExpectations:
  Enabled: false
